return {
	{
		Id = "put_stuff_away",
		Title = "Go to Locker",
		Objective = "Put your stuff in the locker.",
		Type = "Required",
	},
	{
		Id = "get_worksheet",
		Title = "Grab Worksheet",
		Objective = "Grab a worksheet at the front of class.",
		Type = "Required",
	},
	{
		Id = "go_class",
		Title = "Go to Class",
		Objective = "Head to class.",
		Type = "Required"
	},
	{
		Id = "go_library",
		Title = "Go to Library",
		Objective = "Head to the library and sit at the table.",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Head Home",
		Objective = "Head to the door of the school and go home.",
		Type = "Required",
	},
}
