return {
	{
		Id = "put_stuff_away",
		Title = "Go to Locker",
		Objective = "Put your stuff in the locker",
		Steps = "Press E on your locker",
		Type = "Required",
	},
	{
		Id = "get_worksheet",
		Title = "Grab Worksheet",
		Objective = "Grab a worksheet at the front of class",
		Steps = "Press E on the pile of papers",
		Type = "Required",
	},
	{
		Id = "go_class",
		Title = "Go to Class",
		Objective = "Head to class",
		Steps = "Head into the classroom",
		Type = "Required"
	},
	{
		Id = "go_library",
		Title = "Go to Library",
		Objective = "Head to the library and sit at the table",
		Steps = "Head to where your friend is",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Head Home",
		Objective = "Head to the door of the school and go home",
		Steps = "Press E on library door",
		Type = "Required",
	},
}
