local SceneData = {
    SceneId = "Scene2",
    RequiredTasks = {
        "eat_something",
        "talk_to_mom",
        "talk_to_dad",
        "talk_to_sister",
        "go_to_school",
    },

    Objects = {
        Apple = "Apple",
        Cereal = "Cereal",
        Milk = "Milk",
        OrangeJuice = "OrangeJuice",
        Toast = "Toast",
    },

    DialogueIds = {
        IntroThought = "scene2_intro",
        Mom = "scene2_mom",
        Dad = "scene2_dad",
        Sister = "scene2_sister",

    }
}

return SceneData