return {
	{
		Id = "eat_something",
		Title = "Eat Something",
		Objective = "Eat something from the kitchen.",
		Type = "Required",
	},
	{
		Id = "talk_to_mom",
		Title = "Talk to Mom",
		Objective = "Find your mom and talk to her before leaving.",
		Type = "Required",
	},
	{
		Id = "talk_to_dad",
		Title = "Talk to Mom",
		Objective = "Find your dad and talk to him before leaving.",
		Type = "Required",
	},
	{
		Id = "talk_to_sister",
		Title = "Talk to Mom",
		Objective = "Find your sister and talk to her before leaving.",
		Type = "Required",
	},
	{
		Id = "go_to_school",
		Title = "Leave for School",
		Objective = "Head to school and get away from it all.",
		Type = "Required",
	},
}
