return {
	{
		Id = "eat_something",
		Title = "Eat Breakfast",
		Objective = "Grab some breakfast.",
		Type = "Required",
	},
	{
		Id = "grab_apple",
		Title = "Eat Breakfast",
		Objective = "Grab something for breakfast.",
		Type = "Optional",
	},
	{
		Id = "grab_milk",
		Title = "Choose Breakfast",
		Objective = "Choose what to eat.",
		Type = "Optional",
	},
	{
		Id = "grab_oj",
		Title = "Choose Breakfast",
		Objective = "Choose what to eat.",
		Type = "Optional",
	},
	{
		Id = "grab_cereal",
		Title = "Finish Breakfast",
		Objective = "Grab cereal to go with the milk.",
		Type = "Optional",
	},
	{
		Id = "grab_toast",
		Title = "Finish Breakfast",
		Objective = "Grab toast to go with the orange juice.",
		Type = "Optional",
	},
	{
		Id = "talk_to_mom",
		Title = "Talk to Mom",
		Objective = "Talk to Mom before leaving.",
		Type = "Required",
	},
	{
		Id = "talk_to_dad",
		Title = "Talk to Dad",
		Objective = "Talk to Dad before leaving.",
		Type = "Required",
	},
	{
		Id = "talk_to_sister",
		Title = "Talk to Sister",
		Objective = "Talk to your sister before leaving.",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Go to School",
		Objective = "Leave for school.",
		Type = "Required",
	},
}
