return {
	{
		Id = "talk_to_friend",
		Title = "Talk to Friend",
		Objective = "Speak with your friend",
		Steps = "Press E on Friend",
		Type = "Required"
	},
	{
		Id = "sit_at_desk",
		Title = "Sit at Desk",
		Objective = "Take your seat",
		Steps = "Hold E on the open desk",
		Type = "Required"
	},
	{
		Id = "flip_quiz",
		Title = "Take Quiz",
		Objective = "Look at the quiz",
		Steps = "Press E on the paper",
		Type = "Required"
	},
	{
		Id = "go_to_door",
		Title = "Go Home",
		Objective = "Leave the school",
		Steps = "Press E on the front school door",
		Type = "Required"
	},
	{
		Id = "use_charlie_on_quiz",
		Title = "Cheat on Quiz",
		Objective = "Use Charlie on your quiz",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required"
	}
}