return {
	{
		Id = "talk_to_friend",
		Title = "Talk To Friend",
		Objective = "Speak with your friend.",
		Steps = "Press E on Friend.",
		Type = "Required"
	},
	{
		Id = "sit_at_desk",
		Title = "Sit At Desk",
		Objective = "Take your seat.",
		Steps = "Hold E on the open desk.",
		Type = "Required"
	},
	{
		Id = "flip_quiz",
		Title = "Take Quiz",
		Objective = "Look at the quiz.",
		Steps = "Press E on the paper.",
		Type = "Required"
	},
	{
		Id = "go_to_door",
		Title = "Go Home",
		Objective = "Leave the school.",
		Steps = "Interact with the door.",
		Type = "Required"
	},
	{
		Id = "use_charlie_on_quiz",
		Title = "Cheat On Quiz",
		Objective = "Use Charlie on your quiz",
		Steps = "Pess E to talk to Charlie",
		Type = "Required"
	}
}