return {
	{
        Id = "grab_backpack",
        Title = "Grab backpack",
        Objective = "Pick up your backpack",
        Type = "Required",
        Completed = false,
    },
    {
        Id = "grab_calculator",
        Title = "Grab calculator",
        Objective = "Pick up your calculator",
        Type = "Required",
        Completed = false,
    },
    {
        Id = "grab_keys",
        Title = "Grab keys",
        Objective = "Pick up your keys",
        Type = "Required",
        Completed = false,
    },
    {
        Id = "go_to_door",
        Title = "Open door",
        Objective = "Leave your room",
        Type = "Required",
        Completed = false,
    }
}
