local Tasks = {
	{
		Id = "sit_down",
		Title = "Sit Down",
		Description = "Take a seat in class",
		Steps = "Sit down in chair",
		Type = "Required",
	},
	{
		Id = "go_home",
		Title = "Go Home",
		Description = "Leave school and head home",
		Steps = "Press E on door",
		Type = "Required",
	},
	{
		Id = "talk_to_mom",
		Title = "Talk to Mom",
		Description = "Talk to mom about the picture",
		Steps = "Press E on Mom",
		Type = "Required",
	},
}

return Tasks
