return {
    {
        Id = "talk_to_bully",
        Title = "Talk to Bully",
        Objective = "Speak with the bully.",
        Steps = "Walk over to Bully and press E.",
        Type = "Required",
    },
    {
        Id = "go_home",
        Title = "Go home",
        Objective = "Walk out of the school to go home.",
        Steps = "Walk to the door that leads to the front of the school and press interact.",
        Type = "Required",
    },
}