return {
	{
		Id = "talk_about_cheating_on_quiz",
		Title = "Talk to Charlie about cheating on quiz",
		Objective = "Use Charlie.AI to talk to Charlie about the situation regarding cheating on the quiz.",
		Steps = "Press Q or click on Charlie.AI and talk to Charlie about cheating on the quiz.",
		Type = "Required",
	},
	{
		Id = "talk_about_mom_dad_arguing",
		Title = "Talking to Charlie about mom and dad arguing",
		Objective = "Use Charlie.AI to talk to Charlie about mom and dad arguing because of cheating on the quiz.",
		Steps = "Press Q or click on Charlie.AI and talk to Charlie about your parents arguing because of the cheating situation.",
		Type = "Required",
	},
	{
		Id = "talk_about_sis",
		Title = "Talking about feeling guilty for putting sister through this",
		Objective = "Use Charlie.AI to talk to Charlie about feeling guilt over having your sister experience the family issues.",
		Steps = "Press Q or click on Charlie.AI and talk to Charlie about",
		Type = "Required",
	},
	{
		Id = "talk_about_panic_attacks",
		Title = "Talk to Charlie about panic attacks",
		Objective = "Use Charlie.AI to talk to Charlie about the panic attacks you are having.",
		Steps = "Press Q or click on Charlie.AI and talk to Charlie about the panic attacks you're having.",
		Type = "Required",
	},
	{
		Id = "talk_about_judgement_at_school",
		Title = "Talk about judgement at school",
		Objective = "Use Charlie.AI to talk to Charlie about being judged at school.",
		Steps = "Press Q or click on Charlie.AI and talk to Charlie about your experience being judged at school.",
		Type = "Required",
	},
	{
		Id = "go_to_sleep",
		Title = "Go to Sleep",
		Objective = "Rest for the night.",
		Steps = "Interact with your bed.",
		Type = "Required",
	},
}
