return {
	{
		Id = "talk_about_cheating_on_quiz",
		Title = "Talk About Cheating",
		Objective = "Talk to Charlie about cheating on your quiz",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "talk_about_mom_dad_arguing",
		Title = "Talk About Argument",
		Objective = "Talk to Charlie about Mom and Dad arguing",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "talk_about_sis",
		Title = "Talk About Guilt",
		Objective = "Talk to Charlie about guilt for putting sister through this",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "talk_about_panic_attacks",
		Title = "Talk About Emotions",
		Objective = "Talk to Charlie about your emotions",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "talk_about_judgement_at_school",
		Title = "Talk About Judgement",
		Objective = "Talk to Charlie about bullying solutions",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "go_to_sleep",
		Title = "Go to Sleep",
		Objective = "Rest for the night",
		Steps = "Interact with your bed",
		Type = "Required",
	},
}
