local Dialogue = {
    Start = {
        "Im walking down the stairs as always.",
        "Everyday is such a challenge, theres never not one.",
        "What is that soothing noise?",
        "Could it be the rain?.",
    },
    
    Rain = {
        "The rain has always felt calming to me.",
        "Im hopeful for today."
    },
    Crash = {
        "What was that noise?!"
    },
    Mom = {
        "Oh, I did not see you there honey, I accidentally dropped the picture while cleaning.",
        "This picture means nothing anyway."
    },
    Thoughts = {
        "I don’t understand what mom and dad are fighting about.",
        "I did not like the look she was giving me, was breaking the picture on purpose? "
    },
    Eat = {
		"I should eat something."
	},
    Fruit = {
		"I ate some fruit."
	},
	Milk = {
		"I should grab cereal to go with the milk."
	},
	Cereal = {
		"I made some cereal."
	},
	OrangeJuice = {
		"I should make some toast to go with this."
	},
	Toast = {
		"I made some toast."
	},
	Coat = {
		"I grabbed my coat."
	},
	NotReady = {
		"I should finish everything before leaving."
	},
    Final = {
		"Alright, Im ready to go to school."
	}
}

return Dialogue