local Tasks = {
	{
		Id = "grab_apple",
		Title = "Eat Breakfast",
		Objective = "Grab something for breakfast",
		steps = "Press E on a food item",
		Type = "Optional",
	},
	{
		Id = "grab_milk",
		Title = "Eat Breakfast",
		Objective = "Choose what to eat",
		steps = "Press E on a food item",
		Type = "Optional",
	},
	{
		Id = "grab_oj",
		Title = "Eat Breakfast",
		Objective = "Choose what to eat",
		steps = "Press E on a food item",
		Type = "Optional",
	},
	{
		Id = "grab_cereal",
		Title = "Grab Cereal",
		Objective = "Grab cereal to go with the milk",
		steps = "Press E on a food item",
		Type = "Optional",
	},
	{
		Id = "grab_toast",
		Title = "Grab Toast",
		Objective = "Grab toast to go with the orange juice",
		steps = "Press E on a food item",
		Type = "Optional",
	},
	{
		Id = "grab_coat",
		Title = "Grab Coat",
		Objective = "Pick up your coat before leaving",
		steps = "Press E on the coat",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Go to School",
		Objective = "Leave the house",
		steps = "Press E on the door",
		Type = "Required",
	},
	{
		Id = "talk_to_mom",
		Title = "Talk to Mom",
		Objective = "Talk to mom about the picture",
		Steps = "Press E on Mom",
		Type = "Required",
	},
}

return Tasks
