local Tasks = {
	{
		Id = "grab_apple",
		Title = "Eat Something",
		Description = "Grab an apple from the kitchen.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_milk",
		Title = "Eat Something",
		Description = "Grab milk from the fridge.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_oj",
		Title = "Eat Something",
		Description = "Grab orange juice from the fridge.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_cereal",
		Title = "Grab Cereal",
		Description = "Grab cereal to go with the milk.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_toast",
		Title = "Grab Toast",
		Description = "Grab toast to go with the orange juice.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_coat",
		Title = "Grab Coat",
		Description = "Pick up your coat before leaving.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "go_to_door",
		Title = "Go to School",
		Description = "Leave the house.",
		Type = "Required",
		Completed = false,
	},
}

return Tasks