local Tasks = {
	{
		Id = "eat_something",
		Title = "Eat Something",
		Description = "Find something to eat in the kitchen.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_coat",
		Title = "Grab Coat",
		Description = "Pick up your coat before leaving.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "go_to_door",
		Title = "Open Door",
		Description = "Leave the house.",
		Type = "Required",
		Completed = false,
	},
}

return Tasks