return {
	{
		Id = "talk_to_parents",
		Title = "Talk to Parents",
		Objective = "Speak with Mom and Dad.",
		Steps = "Press E on them.",
		Type = "Required"
	},
	{
		Id = "answer_phone",
		Title = "Answer Phone",
		Objective = "The phone is ringing.",
		Steps = "Interact with the phone.",
		Type = "Required"
	},
	{
		Id = "go_to_room",
		Title = "Go to Room",
		Objective = "Run to your room.",
		Steps = "Interact with your bedroom door.",
		Type = "Required"
	},
}