return {
	{
		Id = "talk_to_parents",
		Title = "Talk to Parents",
		Objective = "Speak with Mom and Dad.",
		Steps = "Walk to the living room and press E.",
		Type = "Required",
	},
	{
		Id = "answer_phone",
		Title = "Answer The Phone",
		Objective = "The phone is ringing.",
		Steps = "Interact with the phone.",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Go to Room",
		Objective = "Run away to your room.",
		Steps = "Walk to your bedroom door and interact.",
		Type = "Required",
	},
}