local Tasks = {
	{
		Id = "go_upstairs_to_room",
		Title = "Go Upstairs to Room",
		Description = "Go upstairs to your room.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "do_homework",
		Title = "Do Homework",
		Description = "Work on the homework problem in your room.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "talk_to_charlie",
		Title = "Talk to the AI Chatbot",
		Description = "Use Charlie AI to get help with your homework.",
		Type = "Required",
		Completed = false,
	},
}

return Tasks