local Tasks = {
	{
		Id = "go_upstairs_to_room",
		Title = "Go Upstairs to Room",
		Objective = "Go upstairs to your room",
		Steps = "Walk upstairs to your room",
		Type = "Required",
	},
	{
		Id = "do_homework",
		Title = "Do Homework",
		Objective = "Work on the homework problem in your room",
		Steps = "Press E on homework",
		Type = "Required",
	},
	{
		Id = "talk_to_charlie",
		Title = "Ask Charlie AI",
		Objective = "Use Charlie AI to get help with your homework",
		Steps = "Walk upstairs to your room",
		Type = "Required",
	},
	{
		Id = "go_to_bed",
		Title = "Go to Bed",
		Objective = "Go to bed for the night",
		Steps = "Press E on the bed",
		Type = "Required",
	},
}

return Tasks