return {
	{
		Id = "eat_food",
		Title = "Eat Breakfast",
		Objective = "Find food.",
		Steps = "Interact with the food.",
		Type = "Required"
	},
	{
		Id = "talk_to_sister",
		Title = "Talk to Sister",
		Objective = "Speak with your sister.",
		Steps = "Press E on Sister.",
		Type = "Required"
	},
	{
		Id = "go_to_door",
		Title = "Leave for School",
		Objective = "Head to the door.",
		Steps = "Interact with the door.",
		Type = "Required"
	},
}