return {
	{
		Id = "eat_food",
		Title = "Eat Breakfast",
		Objective = "Get food from the fridge",
		Steps = "Press E on the fridge",
		Type = "Required"
	},
	{
		Id = "find_noise",
		Title = "Find Noise",
		Objective = "Find the source of the crash",
		Steps = "Hint: Downstairs",
		Type = "Required"
	},
	{
		Id = "talk_to_charlie",
		Title = "Talk To Charlie",
		Objective = "Talk to Charlie about problems",
		Steps = "Press Q to interact with Charlie",
		Type = "Required"
	},
	{
		Id = "thank_charlie",
		Title = "Thank Charlie",
		Objective = "Thank Charlie for help",
		Steps = "Press Q to interact with Charlie",
		Type = "Required"
	},
	{
		Id = "talk_to_sister",
		Title = "Talk to Sister",
		Objective = "Speak with your sister.",
		Steps = "Press E on Sister.",
		Type = "Required"
	},
	{
		Id = "go_to_door",
		Title = "Leave for School",
		Objective = "Head to the door.",
		Steps = "Interact with the door.",
		Type = "Required"
	},
}