local Dialogue = {
    Start = {
        "I woke up, but something feels wrong.",
        "I'm so tired of this routine.",
        "Everyday feels horrible, like a never ending loop.",
        "Theres was no day I could wake up and feel any type of excitement.",
        "I better get up before I get lectured by my parents again."
    },
    
    Backpack = {
        "I grabbed my backpack."
    },
    Calculator = {
        "I grabbed my calculator."
    },
    Keys = {
        "I grabbed my keys."
    },
    NotReady = {
        "I should really grab everything before I leave."
    },
    Final = {
        "Alright time to head out."
    }
}

return Dialogue