return {
	{
		Id = "grab_backpack",
		Title = "Grab Backpack",
		Objective = "Pick up your backpack",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_calculator",
		Title = "Grab Calculator",
		Objective = "Pick up your calculator",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_keys",
		Title = "Grab Keys",
		Objective = "Pick up your keys",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "open_door",
		Title = "Open Door",
		Objective = "Leave the bedroom",
		Type = "Required",
		Completed = false,
	}
}