local Tasks = {
	{
		Id = "grab_backpack",
		Title = "Grab Backpack",
		Description = "Pick up your backpack.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_calculator",
		Title = "Grab Calculator",
		Description = "Pick up your calculator.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "grab_keys",
		Title = "Grab Keys",
		Description = "Pick up your keys.",
		Type = "Required",
		Completed = false,
	},
	{
		Id = "go_to_door",
		Title = "Open Door",
		Description = "Leave the bedroom.",
		Type = "Required",
		Completed = false,
	},
}

return Tasks