local Tasks = {
	{
		Id = "grab_backpack",
		Title = "Grab Backpack",
		Objective = "Pick up your backpack",
		Steps = "Press E on the backpack",
		Type = "Required",
	},
	{
		Id = "grab_calculator",
		Title = "Grab Calculator",
		Objective = "Pick up your calculator",
		Steps = "Press E on the calculator",
		Type = "Required",
	},
	{
		Id = "grab_keys",
		Title = "Grab Keys",
		Objective = "Pick up your keys",
		Steps = "Press E on the keys",
		Type = "Required",
	},
	{
		Id = "go_to_door",
		Title = "Leave Room",
		Objective = "Leave the bedroom",
		Type = "Required",
		Steps = "Press E on the door",
	},
}

return Tasks