return {
	{
		Id = "go_to_room",
		Title = "Go to Room",
		Objective = "Walk upstairs to your bedroom",
		Steps = "Walk over to the stairs and walk up",
		Type = "Required",
	},
	{
		Id = "tell_charlie_mom_being_destructive",
		Title = "Talk About Mom",
		Objective = "Talk to Charlie about mom",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "tell_charlie_about_fight_at_school",
		Title = "Talk About Fight",
		Objective = "Talk to Charlie about school fight",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "ask_charlie_for_specific_solution",
		Title = "Get Specific Solution",
		Objective = "Talk to Charlie to find a solution to your problems",
		Steps = "Pess Q to talk to Charlie",
		Type = "Required",
	},
	{
		Id = "grab_computer_cord",
		Title = "Grab Cord",
		Objective = "Look around the room for a computer cord",
		Steps = "Press E on computer cord",
		Type = "Required",
	},
	{
		Id = "do_the_unthinkable",
		Title = "Do the Unthinkable",
		Objective = "Follow the specific solution...",
		Steps = "Press E on chair",
		Type = "Required",
	},
}
