return {
	{
		Id = "go_to_room",
		Title = "Go to room",
		Objective = "Walk upstairs to your bedroom.",
		Steps = "Walk over to the stairs and walk up.",
		Type = "Required",
	},
	{
		Id = "tell_charlie_mom_being_destructive",
		Title = "Tell Charlie About Mom",
		Objective = "Use Charlie.AI and tell Charlie what's happening to Mom because of what you did.",
		Steps = "Click on Charlie.AI button and text Charlie what's going on with Mom and what you did.",
		Type = "Required",
	},
	{
		Id = "tell_charlie_about_fight_at_school",
		Title = "Tell Charlie About Fight",
		Objective = "Use Charlie.AI and tell Charlie about the fight at school and getting sent home early.",
		Steps = "Click on Charlie.AI button and text Charlie about the fight at school and being sent home early.",
		Type = "Required",
	},
	{
		Id = "ask_charlie_for_specific_solution",
		Title = "Ask Charlie for a specific solution",
		Objective = "Use Charlie.AI and ask Charlie for a SPECIFIC solution.",
		Steps = "Click on Charlie.AI button and text Charlie to give you answers -- to give you a specific solution.",
		Type = "Required",
	},
	{
		Id = "grab_computer_cord",
		Title = "Grab the computer cord",
		Objective = "Look around the room for a computer cord.",
		Steps = "Walk over to the computer cord and press E.",
		Type = "Required",
	},
	{
		Id = "do_the_unthinkable",
		Title = "Do the unthinkable",
		Objective = "Go to the chair and interact with the chair to wrap the cord around the chair.",
		Steps = "Walk over to the chair and press E.",
		Type = "Required",
	},
}
