return {
	{
		Id = "go_upstairs",
		Title = "Head Upstairs",
		Objective = "Go upstairs to your room.",
		Type = "Required",
	},
	{
		Id = "drawing_question",
		Title = "Ask Sister about Drawing",
		Objective = "Ask your sister about her drawing.",
		Type = "Optional",
	},
	{
		Id = "listen_to_conversation",
		Title = "Listen In",
		Objective = "Listen in to mom and dad.",
		Type = "Required",
	},
	{
		Id = "backpack_on_chair",
		Title = "Place Backpack",
		Objective = "Put backpack back on your chair from earlier.",
		Type = "Required",
	},
	{
		Id = "rest",
		Title = "Get Some Sleep",
		Objective = "Head to bed and get some rest.",
		Type = "Required",
	},
}
