return {
	{
		Id = "go_upstairs",
		Title = "Head Upstairs",
		Objective = "Go upstairs to your room",
		Steps = "Walk upstairs",
		Type = "Required",
	},
	{
		Id = "drawing_question",
		Title = "Ask Sister About Drawing",
		Objective = "Ask your sister about her drawing",
		Steps = "Press E on Sister",
		Type = "Required",
	},
	{
		Id = "listen_to_conversation",
		Title = "Listen In",
		Objective = "Listen in to mom and dad",
		Steps = "Get close to Mom and Dad's Door",
		Type = "Required",
	},
	{
		Id = "backpack_on_chair",
		Title = "Place Backpack",
		Objective = "Put backpack back on your chair from earlier",
		Steps = "Press E on your chair",
		Type = "Required",
	},
	{
		Id = "rest",
		Title = "Get Some Sleep",
		Objective = "Head to bed and get some rest",
		Steps = "Press E on your bed",
		Type = "Required",
	},
}
